version: "3"

services:
  db:
    image: mysql:5.7
    volumes:
      - .dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shipping_01
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - db
    env_file: .env
